// <auto-generated />
using System;
using ExamTickets.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamTickets.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502222759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamTickets.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.ExamEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("Affirmer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AffirmerLastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Chairman")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CommissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfStatement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsPerTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<int?>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SpecialtyID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("TicketID");

                    b.ToTable("ExamEvents");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpecialtyID")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("SpecialtyID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.QuestionDocument", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UploadedBy");

                    b.ToTable("QuestionDocuments");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Setting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("SettingKey");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            SettingKey = "InstitutionName",
                            SettingValue = "МИНИСТЕРСТВО НАУКИ И ВЫСШЕГО ОБРАЗОВАНИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\nфедеральное государственное автономное образовательное учреждение высшего образования\n«Санкт-Петербургский политехнический университет Петра Великого»\n(ФГАОУ ВО «СПбПУ»)\nИнститут среднего профессионального образования"
                        });
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyID"));

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpecialtyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpecialtyID");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            SpecialtyID = 1,
                            SpecialtyName = "Информационные системы и программирование",
                            SpecialtyNumber = "09.02.07"
                        });
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectID");

                    b.HasIndex("SpecialtyID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID");

                    b.HasIndex("UserID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeacherSubjects", (string)null);
                });

            modelBuilder.Entity("ExamTickets.Core.Models.TicketDocument", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<string>("FilePathDocx")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePathPdf")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("TicketDocuments");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Администратор",
                            IsActive = true,
                            Login = "admin",
                            PasswordHash = "$2a$12$MmqWe0sa1OJNJWRmLn7RCOCr8.N4qthu75Si2I6hZSgmMbp0jsDIi",
                            Role = 0
                        });
                });

            modelBuilder.Entity("ExamTickets.Core.Models.AuditLog", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.ExamEvent", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.User", "CreatedByUser")
                        .WithMany("CreatedExamEvents")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.Group", "Group")
                        .WithMany("ExamEvents")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.QuestionDocument", "QuestionDocument")
                        .WithMany("ExamEvents")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamTickets.Core.Models.Specialty", "Specialty")
                        .WithMany("ExamEvents")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.Subject", "Subject")
                        .WithMany("ExamEvents")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.Teacher", "Teacher")
                        .WithMany("ExamEvents")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.TicketDocument", "TicketDocument")
                        .WithMany("ExamEvents")
                        .HasForeignKey("TicketID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");

                    b.Navigation("QuestionDocument");

                    b.Navigation("Specialty");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("TicketDocument");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Group", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.QuestionDocument", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.Subject", "Subject")
                        .WithMany("QuestionDocuments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamTickets.Core.Models.User", "UploadedByUser")
                        .WithMany("UploadedQuestionDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Subject", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.Specialty", "Specialty")
                        .WithMany("Subjects")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Teacher", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.User", "User")
                        .WithMany("Teachers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.TeacherSubject", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamTickets.Core.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.TicketDocument", b =>
                {
                    b.HasOne("ExamTickets.Core.Models.User", "GeneratedByUser")
                        .WithMany("GeneratedTicketDocuments")
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Group", b =>
                {
                    b.Navigation("ExamEvents");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.QuestionDocument", b =>
                {
                    b.Navigation("ExamEvents");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Specialty", b =>
                {
                    b.Navigation("ExamEvents");

                    b.Navigation("Groups");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Subject", b =>
                {
                    b.Navigation("ExamEvents");

                    b.Navigation("QuestionDocuments");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.Teacher", b =>
                {
                    b.Navigation("ExamEvents");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.TicketDocument", b =>
                {
                    b.Navigation("ExamEvents");
                });

            modelBuilder.Entity("ExamTickets.Core.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedExamEvents");

                    b.Navigation("GeneratedTicketDocuments");

                    b.Navigation("Teachers");

                    b.Navigation("UploadedQuestionDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
